const { ethers } = require('hardhat');
const fs = require('fs');
const path = require('path');

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log('Deploying with account:', deployer.address);

  const TicketNFT = await ethers.getContractFactory('TicketNFT');
  const contract = await TicketNFT.deploy();
  await contract.waitForDeployment();

  const address = await contract.getAddress();
  console.log('TicketNFT deployed to:', address);

  // Read the compiled ABI
  const artifactPath = path.join(__dirname, '..', 'artifacts', 'contracts', 'TicketNFT.sol', 'TicketNFT.json');
  const artifact = JSON.parse(fs.readFileSync(artifactPath, 'utf8'));

  // Write config.js for the frontend
  const configContent = `// Auto-generated by deploy script
const CONTRACT_ADDRESS = '${address}';
const CONTRACT_ABI = ${JSON.stringify(artifact.abi, null, 2)};
`;
  
  const configPath = path.join(__dirname, '..', '..', 'Frontend', 'config.js');
  fs.writeFileSync(configPath, configContent);
  console.log('Frontend config written to:', configPath);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
